module.exports = {
  User: require('./User'),
  Customer: require('./Customer'),
  Product: require('./Product'),
  PriceList: require('./PriceList'),
  DiscountCeiling: require('./DiscountCeiling'),
  ApprovalChainConfig: require('./ApprovalChainConfig'),
  Quotation: require('./Quotation'),
  ScoreSnapshot: require('./ScoreSnapshot'),
  ApprovalStep: require('./ApprovalStep'),
  AuditLog: require('./AuditLog'),
  Warehouse: require('./Warehouse'),
  StockLevel: require('./StockLevel'),
  FulfillmentSplit: require('./FulfillmentSplit'),
  SubscriptionPlan: require('./SubscriptionPlan'),
  BillingSchedule: require('./BillingSchedule'),
  Invoice: require('./Invoice'),
  RepDiscountBaseline: require('./RepDiscountBaseline'),
  DiscountAnomaly: require('./DiscountAnomaly'),
};
